export const paths = {
  HOME: "/",  
  PROFILE: "/profile",
  LOGIN: "/login",
  REGISTER: "/register",
  EXIT: "/exit",
  NOT_FOUND: "/not_found*",
  RESET: "/reset",
  NEWPASSWORD:"/newpassword",
  COURSE:"/course/:id",
  WORKOUT: "/workout",
  WORKOUT_SELECT: "/workout_select",
  PROGRESS:"/progress",
  PROGRESSDONE:"/progressdone",
  SELECTION: "/selection/:id",
}